### ISSUE TITLE
Node requirements within a cluster

### ISSUE THREAD

**Issue by giobart** [edgeIO/src#24]
## Issue description
Right now in order to select a node preference inside the deployment descriptor is possible to use the keyword `node`.
The problem is that specifying this keyword makes the Cluster Orchestrator crash with the error:

```
AttributeError: 'NoneType' object has no attribute 'get'
```
in `cluster_scheduler/calulation.py` line 48

**Did this happen to anybody else?**

In my case the problem is in the line 41,42 and 43 of the same file:

```
41   job_req = job.get('requirements')
42   desired_node = job_req.get('node')
43   node = mongo_find_node_by_name(desired_node)
```

The script search for the 'node' keyword inside the requirements of the job descriptor. 

## Workaround
compile the `deployment descriptor` as in the following example

```
cluster_location: hpi
node: vm-20211019-009
requirements:
    cpu: 0 # cores
    memory: 100  # in MB
    node: vm-20211019-009
```

I specified the `node` keyword twice.

## Possible fix in the code

just change the code as follows:

```
41   job_req = job.get('requirements')
42   desired_node = job.get('node')
43   node = mongo_find_node_by_name(desired_node)
```
