### ISSUE TITLE
Automated deployment helper script 

### ISSUE THREAD

**Issue by giobart** [edgeIO/src#33]
We need an helper tool that:

- Reads a configuration file of the nodes and cluster structure 
- Allows to deploy/undeploy EdgeIO via SSH into these remotes nodes
- Can restart all the worker nodes

**Comment by giobart** [comment]
Current deployment script file format:

```
root:
    hostname: string
    ip: string
    clusters:
        - cluster1_hostname:
            ip: string
            nodes:
                - node1_hostname:
                    ip: string
                - node2_hostname:
                    ip: string
        - cluster2_hostname:
            ip: string
            nodes:
                - node3_hostname:
                    ip: string   

```
